/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package welcomeapp;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    
    public static void main(String[] args) {
		
    	
    	System.out.println("Hello");
    	
    	
    	System.out.println("thank your friends");
    	
    	System.out.println("hello world");
	}
    
   
    
}
