/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package welcomeapp;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
   
    
}
